name: Build APK with Buildozer

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git openjdk-11-jdk unzip zip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Clean previous builds
        run: |
          buildozer android clean

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
